name: Update Wallpapers READMEs

on:
  push:
    branches:
      - main
  schedule:
    # Run every Monday at 3:00 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Generate READMEs
      run: |
        cd .github
        go run .

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '27856297+dependabot-preview[bot]@users.noreply.github.com'

    - name: Commit and Push Changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || \
        (git commit -m "Update wallpapers READMEs [skip ci]" && git push)
